name: python-ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -e .
          pip install pytest black isort mypy
      - name: Lint
        run: |
          . .venv/bin/activate
          black --check src tests
          isort --check-only src tests
          mypy src
      - name: Test
        run: |
          . .venv/bin/activate
          pytest
